# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Secret Base
subtitle: ''
description: ''
keywords:
author: Crazyharp
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://www.crazyharp.icu


permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: prismjs #这一段疑似也不起作用
highlight:
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ""
  exclude_languages:
    - example
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: false
  line_number: true
  line_threshold: 10
  tab_replace: ""
  plugins: []  # 可选择额外插件

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
truncate_len: 50

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: typography
##next

plugin:
  - hexo-generator-category-enhance
  - hexo-generator-feed
  - hexo-asset-image
  - hexo-prism-plugin
  - hexo-toc
  - hexo-prismjs
  - hexo-math
  - markdown-it-container
  - hexo-renderer-markdown-it
  # ... other plugins you'd like to enable

# Generate archive page
archive_generator:
  per_page: 0

# Generate categories index page and each category page
category_generator:
  per_page: 10
  enable_index_page: true
  truncate_len: 50

# Generate tags index page and each tag page
tag_generator:
  per_page: 10
  enable_index_page: true

# Generator atom feed for you website
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# For syntax highlighting
prism_plugin:
  theme: 'base16-ateliersulphurpool.light'
  line_number: true

math: # 这一段疑似不起作用
  enable: true
    # Use Katex for rendering math. Default is false (use MathJax).
  #use_katex: false
  engine: 'mathjax'
    # Katex rendering options (will be ignored if use_katex is false).
  katex:
    delimiters:
      inline: [['$','$'],['\(','\)']]
      block: [['$$','$$'],['\[','\]']]
    # MathJax rendering options (will be ignored if use_katex is true).
mathjax:
    enable: true
    per_page: false
      # MathJax CDN URL (you can modify it to use your local MathJax).
    css: 'https://cdn.jsdelivr.net/npm/hexo-math@4.0.0/dist/style.css'
    cdn: //cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      # MathJax configuration options (see MathJax official documentation for details).
    options:
      tex:
        inlineMath: [['$','$'],['\\(','\\)']]
        displayMath: [['$$','$$'],['\\[','\\]']]
        processEscapes: true


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@121.41.105.96:/www/repo/hexo.git
  branch: master


analytics:
  google_analytics:
    enable: true
    measurement_id: G-WYN5KLV121
  microsoft_clarity:
    enable: false
    project_id: <your project id under Setting, Overview>


toc:
  maxdepth: 2
  class: toc
  slugify: uslug
  decodeEntities: false
  anchor: false
  #  position: after
  #  symbol: '✦'
  #  style: header-anchor

markdown:
  renderer: markdown-it
  plugins:
    - ../../../source/js/hexo-renderermd.js  # 指向自定义配置文件